name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt install libudev-dev pkg-config
    - name: build
      run: cargo build --verbose
    - name: run tests
      run: cargo test --verbose
